# Generated by Django 2.2.13 on 2021-05-19 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0002_auto_20210510_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
