# Generated by Django 2.2 on 2021-05-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0005_auto_20210527_0234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
