# Generated by Django 2.2.13 on 2021-05-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookathon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
